### PR TITLE
feat: macos large runner arm64 builds

### PR DESCRIPTION
**Pull request by Bilb**

### CODE REVIEW

**Comment by Bilb** [comment]
Seems like the arm64 builds we get are broken atm

**Comment by AndreiRegiani** [comment]
> Seems like the arm64 builds we get are broken atm

Can I help with testing?

**Comment by AndreiRegiani** [comment]
Looks like the checks are passing, would be fantastic if macOS ARM makes it into the next release, is there anything missing to make it possible?

**Comment by AndreiRegiani** [comment]
Any update on this? 

image

**Comment by yougotwill** [comment]
@AndreiRegiani Still looking to get this working in the Github Actions but you should see we recently merged a PR to that fixes building arm64 locally. I will investigate https://github.com/oxen-io/session-desktop/issues/3106 sometime this week and see if it resolves this issue 🙏

**Comment by AndreiRegiani** [comment]
@yougotwill @Bilb any updates?

**Comment by AndreiRegiani** [comment]
https://github.com/oxen-io/session-desktop/issues/3106

**Comment by yougotwill** [comment]
Resolved by https://github.com/oxen-io/session-desktop/pull/3163

**Comment by AndreiRegiani** [comment]
What happened? is there an arm64 build for macOS available?

**Comment by yougotwill** [comment]
@AndreiRegiani I made progress and got it working. But we then realized that our auto updater code needed some changes. I tested it locally but we need to investigate setting an an experimental release channel to test the update from an intel build to an arm64 build to make sure nothing breaks. Once that is done then we will ship.

**Pull request closed without merging**
