### PR TITLE
Don't nanny the user. Allow all file types as attachments.

### PR DESCRIPTION
**Pull request by ianmacd**
The Android client already has no such restrictions, and these are ineffective anyway, as they are based on the file's name, not its payload.

### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

This patch allows the desktop client to send an attachment with any type of extension.

### CODE REVIEW

**Comment by Bilb** [comment]
Hey,
Thanks, we want to merge this but tests are failing. Can you please remove all references to `isFileDangerous` ?
You can remove the whole `ts/test/util/isFileDangerous_test.ts` and remove everything in the search results.
image

extra point if you even remove the dangerousFileType reference too (including from the _locales/ files) `-dangerous`

and those styling which will then be unused in `_modules.css`

```ts

.module-message__generic-attachment__icon-dangerous-container {
  position: absolute;

  top: -1px;
  right: -4px;

  height: 16px;
  width: 16px;

  border-radius: 50%;
  background-color: $color-white;
}

.module-message__generic-attachment__icon-dangerous {
  height: 16px;
  width: 16px;

  @include color-svg('../images/error-filled.svg', $session-color-danger);
}
```

**Comment by ianmacd** [comment]
> Hey, Thanks, we want to merge this but tests are failing. Can you please remove all references to `isFileDangerous` ? You can remove the whole `ts/test/util/isFileDangerous_test.ts` and remove everything in the search results. image
> 
> extra point if you even remove the dangerousFileType reference too (including from the _locales/ files) `-dangerous`
> 
> and those styling which will then be unused in `_modules.css`

No problem.

I did it the way I did, because I wasn't sure whether you guys would be open to the premise of the patch at all, and this was the least invasive way to do it and still pass the tests at my end. In that regard, I'm curious why the tests failed for you, as the GitHub build action also didn't flag it to me. Are you using local lint settings?

Anyway, I believe that I've caught all references now, including any other redundancies created by their removal.

**Comment by ianmacd** [comment]
> i'd be very very careful about this because of SVG.

Amusingly. `.svg` wasn't even on the original exclusion list. :-)

**Comment by Bilb** [comment]
That's because we do allow svgs to be uploaded as attachments, but we do not render them as svg but just as generic attachment.

**Review by Bilb — APPROVED** [review]

**Pull request merged**
