### PR TITLE
Enable selection and copying of text of outgoing messages.

### PR DESCRIPTION
**Pull request by ianmacd**
### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

There is still the issue of being able to select and copy text from one's own sent messages.

I'm not sure how else to implement this than by modifying the stylesheet.

### CODE REVIEW

**Comment by Bilb** [comment]
Did you try clearnet today? I merged the fix I was talking about and so far users using clearnet have reported it's ok.

**Comment by ianmacd** [comment]
I did try it and it appeared to work only on incoming messages.

Was I too hasty? I'll try it again and report back.

**Comment by ianmacd** [comment]
Well, this is most odd.

It doesn't work on **all** messages in all groups, and whether they are incoming or outgoing doesn't seem to matter. Leaving the chat, entering another and returning to the original seems to make no difference.

Some messages in some chats have a text body that is reproducibly not selectable. It seems to happen most often to replies, but that may just be a skewed sampling on my part.

Do some messages skip the Emojify action for any reason?

**Comment by Bilb** [comment]
I don't find what is the issue for this as  I did not get any non selectable message in a while. Please open a new issue if you find on what types messages this happens

**Comment by ianmacd** [comment]
> I don't find what is the issue for this as I did not get any non selectable message in a while. Please open a new issue if you find on what types messages this happens

I had tried your fix before and commented on it here:

https://github.com/oxen-io/session-desktop/pull/2216#issuecomment-1070556487

On that occasion, I found that I couldn't consistently select **all** messages, but I will try again and open a new issue if necessary.

**Pull request closed without merging**
