### PR TITLE
Add setting to allow user to specify minimum age of messages to prune from open groups with > 2000 messages.

### LINKED ISSUE #530: Session deletes old messages from large open groups without asking or even informing the user.
When an open group contains more than 2000 messages, Session unilaterally deletes messages older than 6 months without the user's permission or even his knowledge:

https://github.com/oxen-io/session-desktop/blob/8de8f014ddb4ac0cdfcc5bb937a3452b733c54bc/ts/node/sql.ts#L3424-L3452

In my opinion, this constitutes an unacceptable usurpation of the user's control over his own data.

### LINKED ISSUE #2310: Session deletes old messages from large open groups without asking or even informing the user.
When an open group contains more than 2000 messages, Session unilaterally deletes messages older than 6 months without the user's permission or even his knowledge:

https://github.com/oxen-io/session-desktop/blob/8de8f014ddb4ac0cdfcc5bb937a3452b733c54bc/ts/node/sql.ts#L3424-L3452

In my opinion, this constitutes an unacceptable usurpation of the user's control over his own data.

### PR DESCRIPTION
**Pull request by ianmacd**
When an open group has more than 2000 messages, those older than the
specified number of months will be pruned on application start-up.

Fixes oxen-io/session-desktop-temp#421.

image

### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### CODE REVIEW

**Comment by Bilb** [comment]
This doesn't delete all of the messages older than the last 2k messages.

If there is more than 2k messages on a room, it deletes all of the room's messages older than 6 months.
So if you have 200k messages in a room with 60k messages being older than 6 months ago. This cleans up those 60k only and keep the 140k messages which are most recent than 6 months. So the description string is not correct in _locales/en and this PR description neither.

Do we really care about messages older than 6 months old on an opengroup? 
I'll have to check if that's something we want to keep or that will need to stay as a patch.

**Comment by ianmacd** [comment]
> This doesn't delete all of the messages older than the last 2k messages.

I know. I understood how it works.

> If there is more than 2k messages on a room, it deletes all of the room's messages older than 6 months. So if you have 200k messages in a room with 60k messages being older than 6 months ago. This cleans up those 60k only and keep the 140k messages which are most recent than 6 months. So the description string is not correct in _locales/en and this PR description neither.

The PR title could be more accurate, but accuracy comes at the expense of brevity and then it duplicates the description in the body of the PR:

"When an open group has more than 2000 messages, those older than the specified number of months will be pruned on application start-up."

When you say the description is inaccurate, do you mean the above text or the title? After filing this comment, I will endeavour to make the title more accurate, but the description seems good to me. If you disagree, let me know why and I'll be happy to amend it.

> Do we really care about messages older than 6 months old on an opengroup? I'll have to check if that's something we want to keep or that will need to stay as a patch.

"Do we really care about messages older than 6 months old on an opengroup?" is an impossible question to answer on behalf of the user. To answer it, users would need to at least be aware that their older messages are being auto-deleted in this way.

And therein lies my biggest objection to the current behaviour: It's silent, unless the user happens to be in the habit of grepping through the console log. That's nobody. Actually, I do regularly read that log, and I still didn't notice.

In the Session open group, I regularly see repeated requests for an in-app back-up feature, yet behind the scenes Session is silently erasing its own data, a decision made without consulting the user, and without even the courtesy of informing him after the fact.

That's a terrible UX. Data is sacrosanct. One shouldn't make assumptions about its value to someone else, and one certainly shouldn't act on those assumptions without verifying their correctness.

Some users, myself included, want a permanent record of all of their conversations on Session, and that includes those had in open groups, which are just as valuable as private conversations. In my own use case, I scarcely even have any private interactions, so virtually all of the conversations I have are in open groups and rendered impossible to secure by this unilateral policy.

Are the Android and iOS clients similarly configured?

**Comment by fatchan** [comment]
+1 Message history is important, for example in global search. I often want to find an old conversation or message by searching and if they start to disappear without my knowledge or consent... that would suck.

Ian:
> Are the Android and iOS clients similarly configured?

On session-android I can toggle "Delete old messages", pick a "Conversation length limit" (number of messages) and "Trim all conversations now". We should have those same controls on desktop.

**Comment by Bilb** [comment]
Closing this as I'll make a PR with a few changes including
* having a toggle instead of a spinner
* doing those action on app start, if users accepts
* on next update, a dialog will ask user if he wants to enable it or not

**Pull request closed without merging**
