### PR TITLE
Don't show relative timestamp.

### LINKED ISSUE #398: Change the way time is displayed on messages
Change the time display to the Telegram style, where messages have the actual time they were sent, instead of how long they were sent ago. 

image

### LINKED ISSUE #1211: Change the way time is displayed on messages
Change the time display to the Telegram style, where messages have the actual time they were sent, instead of how long they were sent ago. 

image

### PR DESCRIPTION
**Pull request by Mikunj**
Resolves oxen-io/session-desktop-temp#1102

### CODE REVIEW

**Review by BeaudanBrown — APPROVED** [review]
Straightforward, maybe we should just return early for now instead of deleting in case we want to make it a setting to switch between modes later on?

**Comment by Mikunj** [comment]
> Straightforward, maybe we should just return early for now instead of deleting in case we want to make it a setting to switch between modes later on?

Mmm ye we could, @KeeJef thoughts?

**Comment by KeeJef** [comment]
i think we should remove altogether the old setting, i don't think its particularly useful, if its a highly requested feature we could add it back.

**Comment by sachaaaaa** [comment]
Maybe there is a reason I am missing, but why does this PR changes `formatRelativeTime.ts` while the issue is about _not_ showing a relative time but an absolute (local) time instead?

**Comment by Mikunj** [comment]
> Maybe there is a reason I am missing, but why does this PR changes `formatRelativeTime.ts` while the issue is about _not_ showing a relative time but an absolute (local) time instead?

`formatRelativeTime` is the function which gets called when displaying the timestamp. It's weird but signal put their absolute timestamp logic in there aswell so i just left it as is.

**Review by sachaaaaa — APPROVED** [review]

**Pull request merged**
