### PR TITLE
build: fixed better-sqlite3 dependency source

### PR DESCRIPTION
**Pull request by yougotwill**
### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

The chosen source commit hash no longer exists on https://github.com/signalapp/better-sqlite3 so we needed to chose a later commit to use. I tested this manually by rebuilding from source and running `yarn ready` and `yarn start-prod`. Tested on macOS.

### CODE REVIEW

**Comment by peepopoggers** [comment]
does this fix #1635 ?

**Comment by yougotwill** [comment]
@peepopoggers I'm unsure as I don't have a ARM64 device to test with. Please let me know if you manage to build :)

**Comment by Bilb** [comment]
lgtm

**Comment by zpeterg** [comment]
I tried this  here https://github.com/oxen-io/session-desktop/issues/1635#issuecomment-1125453154

**Pull request merged**
