### PR TITLE
add script to create PR for a new release.

### PR DESCRIPTION
**Pull request by Bilb**
needs to be plugged in an action if possible

### CODE REVIEW

**Comment by Mikunj** [comment]
Re: Github actions
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#release

**Comment by GeopJr** [comment]
Just noticed this PR,
a different way to achieve auto-PRs on the flatpak would be using https://github.com/flathub/flatpak-external-data-checker, which automatically checks updates on the url and PRs.

However, currently it seems that it has problems with GitHub releases because it follows redirects, leading to situations like this:
https://github.com/flathub/org.lamport.tla.toolbox/pull/23/files
and PR spam https://github.com/flathub/org.lamport.tla.toolbox/pulls?q=is%3Apr+is%3Aclosed.

There's a PR for the above issue, but it hasn't been merged yet https://github.com/flathub/flatpak-external-data-checker/pull/90

(The signal flatpak also uses the flatpak-external-data-checker since signal hosts the packages on their servers)

**Comment by gasinvein** [comment]
@GeopJr FYI the json checker is not ready just yet, but there is now [another one](https://github.com/flathub/flatpak-external-data-checker#anitya-release-monitoring-checker) usable to check github releases.

**Comment by GeopJr** [comment]
> @GeopJr FYI the json checker is not ready just yet, but there is now [another one](https://github.com/flathub/flatpak-external-data-checker#anitya-release-monitoring-checker) usable to check github releases.

Thank you so much!

**Pull request closed without merging**
