### PR TITLE
Add settings toggle to require [Shift] + [Enter] to send a message.

### PR DESCRIPTION
**Pull request by ianmacd**
Most messaging clients have such a setting to avoid accidental sending
when [Enter] is pressed, and/or make typing long messages easier.

### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

This adds a new setting to allow message sending to occur only when `Shift`+`Enter` is pressed.

image

### CODE REVIEW

**Comment by KeeJef** [comment]
Isn't shift+enter usually used for new line? I guess if this is turned on enter creates a new line, and shift+enter becomes send, either way might want to update the wording on this one to make that clear. Should be off by default.

**Comment by ianmacd** [comment]
> Isn't shift+enter usually used for new line? I guess if this is turned on enter creates a new line, and shift+enter becomes send, either way might want to update the wording on this one to make that clear. Should be off by default.

Yes, `[Shift]` + `[Enter]` normally gives a new line. All this patch does is swap the effect of shifted `[Enter]` with that of unshifted `[Enter]`, so that the key in its unshifted state will now give a new line.

I'll rebase in a second with clarified wording in the strings.

**Comment by ianmacd** [comment]
The new wording:

image

**Comment by beantaco** [comment]
> Isn't shift+enter usually used for new line? I guess if this is turned on enter creates a new line, and shift+enter becomes send, either way might want to update the wording on this one to make that clear. Should be off by default.

Seeing the Shift + Enter proposal made me think for a moment too. I thought Ctrl + Enter may be better, but I may be wrong. Is Shift + Enter based on anything?

I suggest conducting a quick but wide enough survey of existing apps that commonly have both send/confirm and new line functionality, and deciding based on that. Some desktop/web software I can think of off the top of my head: Element (Matrix), LibreOffice, Mattermost, Microsoft Office, Signal, Slack.

**Comment by KeeJef** [comment]
Is there any community support for this?

**Comment by ianmacd** [comment]
> Is there any community support for this? Does anyone want this option added personally?

Well, I haven't heard people ask for it, but an option to avoid having an accidental `[Enter]` send a half-written message is a feature of most messaging clients.

#2249 is related to this and a much more useful patch, in my opinion. Even Telegram doesn't have the functionality of that patch.

**Comment by KeeJef** [comment]
This has been implemented and merged here https://github.com/oxen-io/session-desktop/pull/2955 according to copy and designs here https://github.com/oxen-io/session-desktop/issues/1486 , thanks for raising this PR

**Pull request closed without merging**
