### PR TITLE
Disable drag n drop temporarily

### LINKED ISSUE #181: Disable drag'n'drop
Disable drag n drop until we support attachments.

### LINKED ISSUE #1296: Disable drag'n'drop
Disable drag n drop until we support attachments.

### PR DESCRIPTION
**Pull request by sachaaaaa**
fixes oxen-io/session-desktop-temp#1186

### CODE REVIEW

**Comment by Mikunj** [comment]
We might actually want to disable pasting anything other than text as well.

**Comment by sachaaaaa** [comment]
Good catch, will look into it.

**Review by BeaudanBrown — APPROVED** [review]
Straight forward

**Review by Mikunj — APPROVED** [review]

**Comment by sachaaaaa** [comment]
Note that commenting out `onPaste` still allows pasting text.

**Pull request merged**
