### PR TITLE
Enable selection and copying of text of incoming and outgoing messages.

### PR DESCRIPTION
**Pull request by ianmacd**
### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

At some point, the ability to select and copy text from previous messages was lost. This restores it.

Being able to copy and paste from previous messages is a very useful feature.

### CODE REVIEW

**Comment by Bilb** [comment]
Hey,

Actually this is a mistake I made and the correct fix is I think

```
modified: ts/components/conversation/Emojify.tsx
───────────────────────────────────────────────────────────
@ ts/components/conversation/Emojify.tsx:44 @ export const Emojify = (props: Props): JSX.Element => {
    default:
  }

  return <span style={{ fontSize: `${size}em` }}>{rendered}</span>;
  return <span style={{ fontSize: `${size}em`, userSelect: 'inherit' }}>{rendered}</span>;
};

**Comment by ianmacd** [comment]
> Hey,
> 
> Actually this is a mistake I made and the correct fix is I think

Ah, sweet.

I couldn't find what had caused the breakage, so I was aware that I was probably fixing it the wrong way. I wasn't sure that the change in behaviour was accidental either, but I couldn't imagine a reason for it being deliberate.

I assume you'll be committing your change. When I see it, I'll close this PR.

**Comment by ianmacd** [comment]
Actually, that fix enables selecting and copying on incoming messages only.

Is there an easy fix that also allows text from one's own messages to be selected and copied?

**Comment by Bilb** [comment]
this fix works fine for each messages for me

https://user-images.githubusercontent.com/1544279/158526323-aea2c007-9e41-4429-8114-c893445d3347.mp4

.

**Comment by Bilb** [comment]
I'll get this included in a PR of mine as we want this fixed for the upcoming release

**Pull request closed without merging**
