### PR TITLE
fix typo call missed toast 

### PR DESCRIPTION
**Pull request by Bilb**
send message to him => send message to them

### CODE REVIEW

**Comment by ericnething** [comment]
This is grammatically incorrect, as "them" is plural, meaning it is not suitable to use in reference to an individual. The correct form is "him", as has been used for thousands of years, and does not explicitly exclude the possibility that the person being referenced is female. The root of this "them" confusion is political activism by the willfully ignorant who are chasing a false sense of importance, but are unaware of being pawns for the globalists who wish to enslave us all without firing a single bullet. The erasure of any concept of sex (male and female) is part of the destruction of the family, the central foundation on which society is built. Without family, people turn to the government and mega corporations as their surrogate family, and thus we have Brave New World. This is censorship, plain and simple.

If "them" was truly singular, we could use it in place of any other singular pronoun and have the sentence still make sense, which is a rule of pronouns, but we cannot, because it is plural. Example:
> 1. He is going to the store.
> 2. They is going to the store.

We can see that the second example is clearly wrong, as it sounds like a 5-year-old trying to speak English.

**Comment by KeeJef** [comment]
Them is more correct in this scenario and it has nothing to do with politics. 

> "Call missed from '$name$' as you haven't approved this conversation yet. Send a message to him first."
> "Call missed from '$name$' as you haven't approved this conversation yet. Send a message to them first."

We don't know the the gender of the person who you missed a call for so them makes total sense

**Comment by ericnething** [comment]
I just explained why "them" is not correct --- because it is plural, not singular. The only reason for this incorrect usage is to push a political agenda, as mentioned.

**Comment by novacoole** [comment]
@ericnething

[https://en.wikipedia.org/wiki/Singular_they](https://en.wikipedia.org/wiki/Singular_they)
Whether or not it is "grammatically correct" is not certain, and there has been disagreements on this for at least 600 years in the english language, however:

> A study of whether "singular they" is more "difficult" to understand than gendered pronouns found that "singular they is a cognitively efficient substitute for generic he or she, particularly when the antecedent is nonreferential" (e.g. anybody, a nurse, or a truck driver) rather than referring to a specific person (e.g. a runner I knew or my nurse). Clauses with singular they were read "just as quickly as clauses containing a gendered pronoun that matched the stereotype of the antecedent" (e.g. she for a nurse and he for a truck driver) and "much more quickly than clauses containing a gendered pronoun that went against the gender stereotype of the antecedent". - [Relevant study](https://web.archive.org/web/20150502082946/http://gernsbacherlab.org/wp-content/uploads/papers/1/Foertsch_Gender-Neutrality-They-or-He_PS_1997.pdf)

Considering it has little impact on cognitive efficiency, I believe it makes sense to use "them" in this instance as the gender is unknown and this usecase is commonplace within the english language, even outside of communities with gender-neutral people, for example:
> Who is that way over there, what are they doing? I can't quite see them.

**Pros of using them:** 
- Inclusivity
- Avoiding needlessly attributing gender to otherwise anonymous individuals (this is a privacy application after all).

**Cons of using them:**
- Frustration of traditional grammar nerds.

**Pull request merged**
