### PR TITLE
vacuum database on migration + enable secure delete

### PR DESCRIPTION
**Pull request by Bilb**
relates oxen-io/session-desktop-temp#712

### CODE REVIEW

**Comment by jimgillo** [comment]
For more security, you should add in your code:

**pragma secure_delete=on**

https://www.tutorialspoint.com/sqlite/sqlite_pragma.htm
https://www.oreilly.com/library/view/using-sqlite/9781449394592/re201.html

For erased messages to be deleted in any case (even if Session is not restart).

**Comment by Bilb** [comment]
@jimgillo I put those steps in amigration. I think we are good like that right?
Performance wise this looks to be fine

**Comment by jimgillo** [comment]
what do you mean by vaccum database on migration? vacuum database shoould be used at the startup of session messenger.

**Comment by Bilb** [comment]
right right. I thought that the secure_erase was handling vaccuum but it just feels the reclaimed bytes with 0, so we still need to vacuum them out.

**Pull request merged**
