### PR TITLE
Use accent colour to distinguish last read indicator.

### PR DESCRIPTION
**Pull request by ianmacd**
### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

The dark mode accent colour (Session green) provides much better contrast for the ruler line and text indicating the boundary between previously seen messages and new messages.

image

### CODE REVIEW

**Comment by Bilb** [comment]
this will only applies on dark mode. It's not readable to have the same change for the light mode?

**Comment by ianmacd** [comment]
> this will only applies on dark mode. It's not readable to have the same change for the light mode?

It changes the colour of the text in light mode, too, due to the change to `SessionLastSeenIndicator.tsx`

Here, the green on white text isn't ideal, but could be fixed:

image

**Comment by Bilb** [comment]
I'll make it like that for the light theme
image
image

**Comment by ianmacd** [comment]
> I'll make it like that for the light theme

Looks good.

**Pull request merged**
