### PR TITLE
Make sure we are purging nodes from retrieve swarm list, and also filter 0.0.0.0 ips when getting snodes from wrong swarm error

### PR DESCRIPTION
**Pull request by BeaudanBrown**
Hopefully fixes or at least improves oxen-io/session-desktop-temp#1123

### CODE REVIEW

**Comment by sachaaaaa** [comment]
Is it really necessary to filter the snodes again in `updateSwarmNodes` ?

It looks like we already filter upstream in `getSwarmNodes` (loki_snode_api.js:194) ...
```js
const snodes = result.snodes.filter(snode => snode.ip !== '0.0.0.0');
```

**Comment by BeaudanBrown** [comment]
Right sorry I should have ported my comment from the issue over to this PR
Explanation is here

Ah I think I know one of the potential problems
He got a `WrongSwarmError` which usually indicates that they had been using the app some time in the past and then hadn't opened it for a while so the swarm state has changed since then
And we forgot to filter out `0.0.0.0` addresses (which is what lokid reports if it hasn't received an uptime proof from that node so it doesn't know it's ip/port) when we update swarms through the wrong swarm error. So he is reporting a bunch of `request to https://0.0.0.0:0/storage_rpc/v1 failed, reason: connect EADDRNOTAVAIL`
The latest storage server should be filtering these out on the other end so there might be some outdated storage server binaries on the testnet. Plus there were way too many failed requests which pointed me to another bug where checking with this magic number in one place
```js
if (successiveFailures >= 3) {
  await lokiSnodeAPI.unreachableNode(this.ourKey, address);
}
```
And then with this constant `const MAX_ACCEPTABLE_FAILURES = 1;` in other places so we were never actually purging the failed nodes for retrieving connections

**Comment by sachaaaaa** [comment]
Ok, so this is purely to purge bad cached data?

**Comment by BeaudanBrown** [comment]
The issue was that in `loki_message_api` we were doing this
```js
          if (e instanceof textsecure.WrongSwarmError) {
            const { newSwarm } = e;
            await lokiSnodeAPI.updateSwarmNodes(this.ourKey, newSwarm);
            for (let i = 0; i < newSwarm.length; i += 1) {
              const lastHash = await window.Signal.Data.getLastHashBySnode(
                newSwarm[i]
              );
              this.ourSwarmNodes[newSwarm[i]] = {
                lastHash,
              };
            }
            // Try another snode
            break;
```
I.e. getting the swarm information through the failed response to the snode, not through `getSwarmNodes`
Ideally it would be nice to *only* put the filtering in `updateSwarmNodes`, but currently in some places we call `getFreshSwarmNodes` which just returns the list of nodes from `getSwarmNodes` and then pass that list on to `updateSwarmNodes` while also using it locally
So one option could be to make this function
```js
  async refreshSwarmNodesForPubKey(pubKey) {
    const newNodes = await this.getFreshSwarmNodes(pubKey);
    this.updateSwarmNodes(pubKey, newNodes);
  }
```
return the fresh swarm nodes and put the filtering logic in there and only ever call that when we want fresh swarm nodes?

**Review by Mikunj — APPROVED** [review]

**Review by sachaaaaa — APPROVED** [review]
Ok, thanks for the insight. I think the PR is a good way to handle this then!

**Pull request merged**
