### PR TITLE
Various improvements to the display of unread conversation and unread message counts.

### PR DESCRIPTION
**Pull request by ianmacd**
### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

Various fixes for tracking the unread message count:

* There's now no cap on the number of unread messages reported. Arbitrarily imposing an upper bound on this doesn't seem useful to me, so I have removed it.
* For the same reason, there's now also no cap on the number of unread conversations reported.
* The number of unread conversations is now reported with the total number of unread messages across all conversations.
* The scroll-to-bottom button is now overlaid with the number of messages still unread in the currently selected conversation.

If you don't want all of these changes, just pick and choose the parts you want.

It's getting harder for me over time to submit modular pull-requests, because my own fork is steadily diverging from upstream and the features I add are slowly introducing dependencies between pull-requests, some of which have already been rejected upstream.

The dual unread convo/unread message count from the action panel:

image

Examples of the unread message count atop the scroll-to-bottom. The position auto-adjusts, based on the width (i.e. number of digits) of the count:

chevron10chevron9chevron8chevron7chevron6

### CODE REVIEW

**Comment by KeeJef** [comment]
Spoke with the team about these changes, we all liked the inclusion of the unread count on the scroll down button and are happy to merge this if alignment issues are fixed. 

However other elements of the PR we don't see as necessary, removing caps on the number of unread messages displayed can clutter the interface and overwhelm the user with information which isn't really useful. 

The dual unread convo/unread message count is cool, but visually it looks unprofessional, its not exactly clear what it means by just looking at the icon.

**Comment by ianmacd** [comment]
> Spoke with the team about these changes, we all liked the inclusion of the unread count on the scroll down button and are happy to merge this if alignment issues are fixed.

I'll look at fixing the alignment.

> However other elements of the PR we don't see as necessary, removing caps on the number of unread messages displayed can clutter the interface and overwhelm the user with information which isn't really useful.

Well, the character count difference between `9999+` and a 5-digit **unread message count** is 0, so we literally gain an order of magnitude in count accuracy for no increase in element width. Removing the cap doesn't actually result in more interface clutter until the user has more than 99,999 unread messages. That's a lot. I wonder whether such a user currently exists and, if he does, whether the extra digit would truly "overwhelm" him.

I suggest this consideration is almost certainly a non-issue, and that open-group pruning (i.e. the removal of old messages in large open groups) would kick in and take care of this edge case anyway.

Similarly, once the **number of unread conversations** rises to 100, the number of characters required to display `99+` is 3. Again, abandoning the `+` here and instead using that character for the actual count provides us with an order of magnitude more accuracy up to 999 without increasing the width of the element. So here again, no actual interface clutter arises.

The only users theoretically burdened with an extra digit are those with more than 999 unread conversations. I suggest that the number of users who even **administer** more than 999 conversations is infinitesimal, and that the number of them who have more than 999 **unread** conversations is almost certainly 0. Again, this seems a non-issue to me.

> The dual unread convo/unread message count is cool, but visually it looks unprofessional, its not exactly clear what it means by just looking at the icon.

I agree it doesn't look good, but I couldn't think of a better alternative within the space constraints that apply. I'm open to ideas.

**Comment by RubenGarcia** [comment]
I would like to see this merged. Thanks!

**Comment by Bilb** [comment]
going to be merged as part of

**Comment by Bilb** [comment]
https://github.com/oxen-io/session-desktop/pull/2996

**Pull request closed without merging**
