### PR TITLE
Add toggle to discard message requests instead of blocking the senders.

### PR DESCRIPTION
**Pull request by ianmacd**
### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description

The current implementation of message requests bothers me.

When a request is declined or the whole message request queue is cleared, the message(s) in question are not simply discarded. Instead, the senders of those messages are blocked.

The consequences of this are much too harsh. Not only is the user unable to contact me ever again, even to send a future request, all messages from that user will henceforth also be filtered from open groups. Since most message requests result from a recent discussion in an open group, this is far from an ideal outcome. The flow of the open groups is disrupted by this behaviour.

Such users are typically not malicious. They just want to talk. I don’t want to block them; I just turn down their request to talk at this time. I want them to be able to send another request in the future. And I certainly don’t want my response to their request to affect my ability to follow discussions in open groups.

To this end, I have written this patch, which makes user-configurable the action to be taken when a message request is refused. Instead of blocking the message’s sender, the user can instead elect to simply discard the message.

### CODE REVIEW

**Comment by KeeJef** [comment]
I don't think we should toggle this in settings, probably we should just just ask the user when denying a message request whether they just want to delete the message request or delete + block, either that or display a button to accept / delete or / delete and block, not sure what that will look like UI wise.

**Comment by ianmacd** [comment]
> I don't think we should toggle this in settings, probably we should just just ask the user when denying a message request whether they just want to delete the message request or delete + block, either that or display a button to accept / delete or / delete and block, not sure what that will look like UI wise.

That would be an OK way to handle it, although I'd personally (almost) never want to block, so I'd get tired of answering the question with the same answer every time.

The most important thing is giving the user the choice, which isn't done at the moment. Not only that, but the verbiage used gives no indication that users are actually being blocked.

**Comment by Bilb** [comment]
I will need to loopback with the other platforms to  see how we can handle this

**Comment by ianmacd** [comment]
> I will need to loopback with the other platforms to see how we can handle this

Cool.

Above, you'll see that @KeeJef made the suggestion of allowing the user to decide on a per instance basis. If the user is likely to want to delete+block sometimes, but delete+discard other times, then his is the better suggestion. Knowing only my own habits, it's impossible to make that call without putting it out to user testing.

**Comment by Bilb** [comment]
Closing this in favor of https://github.com/oxen-io/session-desktop/pull/2466

**Pull request closed without merging**
