### PR TITLE
Registration progress banner

### PR DESCRIPTION
**Pull request by warrickct**
* Adds a small banner for instruction on storing recovery phrase securely on first signup. Banner fades away once the user copies their phrase.
* Also adds deletion of redux persisted settings upon account deletion.

progress-banner
progress-banner2
progress-banner-3

### CODE REVIEW

**Comment by Bilb** [comment]
I am not 100% sure about the difference between those two screens. Why cannot they be one only? User click on the button, and the seed is displayed, no ?
> progress-banner
> progress-banner2


I think it would be enough to just open the Seed dialog to let the user copy its seed from there, rather than showing that part of the UI: 
> progress-banner-3

**Comment by warrickct** [comment]
@Bilb  Sure, I can combine them. It was just based off the original design on Android. Sure thing, I can also move the recovery phrase part to a modal dialog.

**Comment by Bilb** [comment]
> @Bilb Sure, I can combine them. It was just based off the original design on Android. Sure thing, I can also move the recovery phrase part to a modal dialog.

there is already a seed dialog. It's the one shwon on click on the settings => show recovery phrase button. Just display this one when the user clicks on your button

**Comment by warrickct** [comment]
> > @Bilb Sure, I can combine them. It was just based off the original design on Android. Sure thing, I can also move the recovery phrase part to a modal dialog.
> 
> there is already a seed dialog. It's the one shwon on click on the settings => show recovery phrase button. Just display this one when the user clicks on your button

Yup I saw that modal. I've added it in this morning, I was just refactoring it to a functional component. Just a few minor changes after lunch and I'll push the changes.

**Pull request merged**
